aws:
  credentials:
    accessKey: xxx
    secretKey: xxx
  s3:
    zone: xxx
    bucket:
      name: xxx
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: Marius
          jwk-set-uri: http://auth-server:9000/api/.well-known/jwks.json

  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas: inventory
  datasource:
    hikari:
      max-lifetime: 600000
      idle-timeout: 600000
    driverClassName: org.postgresql.Driver
    password: inventory_x
    username: inventory_x
    url: jdbc:postgresql://xxx/postgres
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: inventory
  graphql:
    graphiql:
      enabled: true
  servlet:
    multipart:
      max-request-size: 1280KB
      max-file-size: 1280KB
      enabled: true
server:
  servlet:
    context-path: /api
  port: '9001'
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        security: DEBUG
