spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: Marius
          jwk-set-uri: http://auth-server:9000/api/.well-known/jwks.json
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  datasource:
    driverClassName: org.h2.Driver
    password: inventory_x
    username: inventory_x
    url: jdbc:h2:file:~/inventory_DB
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'false'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  graphql:
    graphiql:
      enabled: true
server:
  servlet:
    context-path: /api
  port: '9001'
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        security: DEBUG
