spring:
  application.name: elastic-indexer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://account-service:9000
  elasticsearch:
    username: spring_user
    password: spring_user123
    hostname: localhost
    port: 9200
    scheme: https
    ssl: false
  #    uris: https://localhost:9200

services:
  inventory:
    url: http://localhost:9001
  account:
    url: http://localhost:9000

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        security: DEBUG

indexer:
  initialization:
    enabled: true
    filepath: phone_dataset.xlsx