spring:
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas: account
  datasource:
    hikari:
      max-lifetime: 600000
      idle-timeout: 600000
    driverClassName: org.postgresql.Driver
    password: account_x
    username: account_x
    url: jdbc:postgresql://XXX
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: account
server:
  servlet:
    context-path: /api
  port: '9000'

jwt:
  claims:
    custom:
      issuer: Marius
      expiry: 36000
  public:
    key: classpath:rsa.public.key
  private:
    key: classpath:rsa.private.key


logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        security: DEBUG