server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://account-service:9000
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /sessions/$\{segment}
        - id: inventory-service
          uri: http://inventory-service:9001
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /api/$\{segment}
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        security: DEBUG

security:
  oauth2:
    jwt:
      issuerUri: http://account-service:9000/oauth2/jwks